# Generated by Django 3.2.21 on 2023-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://asset.cloudinary.com/dj3sy6ut7/228e9133b459c25fac28a4eebb2ef749', upload_to='images/'),
        ),
    ]
