# Generated by Django 3.2.21 on 2023-09-24 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('10:00 am - 11:30 am', '10:00 am - 11:30 am'), ('12:00 pm - 1:30 pm', '12:00 pm - 1:30 pm'), ('4:00 pm - 5:30 pm', '4:00 pm - 5:30 pm'), ('6:00 pm - 7:30 pm', '6:00 pm - 7:30 pm')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('num_people', models.PositiveIntegerField(default=1)),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiting.timeslot')),
            ],
        ),
    ]
