# Generated by Django 3.2.21 on 2023-09-26 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('10:00 am - 11:30 am', '10:00 am - 11:30 am'), ('12:00 pm - 1:30 pm', '12:00 pm - 1:30 pm'), ('4:00 pm - 5:30 pm', '4:00 pm - 5:30 pm'), ('6:00 pm - 7:30 pm', '6:00 pm - 7:30 pm')], max_length=50)),
                ('max_capacity', models.PositiveIntegerField(default=28)),
                ('num_of_people', models.PositiveIntegerField(default=1)),
                ('current_capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
