# Generated by Django 3.2.21 on 2023-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
