# Generated by Django 3.2.21 on 2023-10-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='section',
            field=models.CharField(choices=[('Museum', 'Museum'), ('Photos Gallery', 'Photos Gallery'), ('Underground Wine tanks', 'Under Ground Wine tanks'), ('Private Garden', 'Private Garden')], default='Choose here!', max_length=100),
        ),
    ]
