# Generated by Django 3.2.21 on 2023-10-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0002_booking_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='post',
        ),
    ]
