# Generated by Django 3.2.21 on 2023-09-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0002_timeslot_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
