# Generated by Django 3.2.21 on 2023-11-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0003_remove_booking_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='section',
            field=models.CharField(choices=[('Museum', 'Museum'), ('Photos Gallery', 'Photos Gallery'), ('Underground Wine tanks', 'Underground Wine tanks'), ('Private Garden', 'Private Garden')], default='Museum', max_length=100),
        ),
    ]
