# Generated by Django 3.2.21 on 2023-09-24 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0003_timeslot_booked_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='booked_count',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='max_capacity',
        ),
    ]
