# Generated by Django 3.2.21 on 2023-09-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0004_auto_20230924_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='booked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
