# Generated by Django 3.2.21 on 2023-11-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0004_alter_booking_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='section',
            new_name='tour_section',
        ),
    ]
