# Generated by Django 3.2.21 on 2023-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0005_auto_20230924_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='num_of_people',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='max_capacity',
            field=models.PositiveIntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00 am - 11:30 am', '10:00 am - 11:30 am'), ('12:00 pm - 1:30 pm', '12:00 pm - 1:30 pm'), ('4:00 pm - 5:30 pm', '4:00 pm - 5:30 pm'), ('6:00 pm - 7:30 pm', '6:00 pm - 7:30 pm')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
