# Generated by Django 3.2.21 on 2023-09-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0006_auto_20230924_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='current_capacity',
        ),
    ]
