# Generated by Django 3.2.21 on 2023-09-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0007_remove_booking_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
