# Generated by Django 3.2.21 on 2023-09-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visiting', '0008_booking_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='current_capacity',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='visit_bookings', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.PositiveSmallIntegerField(choices=[(1, '10:00 am - 11:30 am'), (2, '12:00 pm - 1:30 pm'), (3, '4:00 pm - 5:30 pm'), (4, '6:00 pm - 7:30 pm')]),
        ),
    ]
