# Generated by Django 3.2.21 on 2023-09-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0013_alter_booking_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
