# Generated by Django 3.2.21 on 2023-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting', '0014_booking_current_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00 am - 11:30 am', '10:00 am - 11:30 am'), ('12:00 pm - 1:30 pm', '12:00 pm - 1:30 pm'), ('4:00 pm - 5:30 pm', '4:00 pm - 5:30 pm'), ('6:00 pm - 7:30 pm', '6:00 pm - 7:30 pm')], max_length=50),
        ),
    ]
