# Generated by Django 3.2.21 on 2023-09-19 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_timeslot', models.TimeField(choices=[('10:00', '10:00 AM - 11:30 AM'), ('12:00', '12:00 PM - 1:30 PM'), ('16:00', '4:00 PM - 5:30 PM'), ('18:00', '6:00 PM - 7:30 PM')], default='10:00')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
