# Generated by Django 3.2.21 on 2023-09-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='max_capacity',
            field=models.PositiveIntegerField(default=17),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(choices=[('10:00 am - 11:30 am', '10:00 am - 11:30 am'), ('12:00 pm - 1:30 pm', '12:00 pm - 1:30 pm'), ('4:00 pm - 5:30 pm', '4:00 pm - 5:30 pm'), ('6:00 pm - 7:30 pm', '6:00 pm - 7:30 pm')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
