# Generated by Django 3.2.21 on 2023-09-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230920_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='current_capacity',
        ),
    ]
