# Generated by Django 3.2.21 on 2023-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
