# Generated by Django 3.2.21 on 2023-09-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_booked_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_count',
            new_name='current_capacity',
        ),
    ]
