# Generated by Django 3.2.21 on 2023-09-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_booked_count_booking_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='max_capacity',
        ),
    ]
