# Generated by Django 3.2.21 on 2023-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
