# Generated by Django 3.2.21 on 2023-09-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_count',
        ),
    ]
