# Generated by Django 3.2.21 on 2023-09-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_rename_booking_count_booking_booked_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
